### ISSUE TITLE
Only set ssh key_name if desired by the user

### ISSUE THREAD

**Issue by bhagemeier** [EGI-FCTF/rOCCI-cli#20]
When providing an SSH key from the command line, rOCCI-CLI always sets a (hard-coded) name for it accordingly. This does not work in OpenStack, as keys can only be registered once under a name and not be overwritten.

See discussion at https://bugs.launchpad.net/ooi/+bug/1527261/ and particularly comment 4 for further information.

Cheers,
Björn

**Comment by arax** [comment]
Yes, this is a valid issue. We are currently setting the `publickey.name` attribute to a static value [1].

[1] https://github.com/EGI-FCTF/rOCCI-cli/blob/master/lib/occi/cli/helpers/create_helper.rb#L116

**Comment by arax** [comment]
@bhagemeier I have an additional question, if I may. What happens if `name` is not specified? Can I simply leave all keys nameless? Or can I generate a new name every time? In the future, this way of providing credentials will be deprecated in favor of `user_data`. I'm looking for a quick fix here.

Thanks!

**Comment by enolfc** [comment]
If name is not specified, a key with a uuid name is created in OpenStack. We probably need to check in ooi for a way of not overloading the site with user's key that are actually the same one (probably we may also hit quotas easily). I think the easiest way forward is to could leave all keys nameless.

**Comment by arax** [comment]
@enolfc Ok, will do.

**Comment by arax** [comment]
Issue fixed in `v4.3.4`. Packages will be available shortly.
